/*
 * WelcomeView.java
 *
 * Created on 2010-4-28, 15:31:54
 */

package org.mepper.app;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JFrame;

import org.zhiwu.app.AppManager;
import org.zhiwu.utils.AppResources;

/**
 * <B>WelcomeView</B>
 * 
 * @author Brook Tran. Email: <a href="mailto:Brook.Tran.C@gmail.com">Brook.Tran.C@gmail.com</a>
 * @version Ver 1.0.01 2011-9-28 created
 * @since org.mepper.app Ver 1.0
 * 
 */
public class WelcomeView extends javax.swing.JFrame {
	private final AppResources  r=AppManager.getResources();

    /** Creates new form WelcomeView */
    public WelcomeView() {
    	this(5);
    }

    int i=0;
	public WelcomeView(int stepCount) {
		initComponents();
		jProgressBar1.setValue(stepCount);
		setIconImage(AppManager.getResources().getImage("system"));
	}

		public void setText(String text) {
			jLabel1.setText(text);
			jLabel1.paintImmediately(jLabel1.getBounds());
			jProgressBar1.setValue(jProgressBar1.getValue()+10);
		}

		
		public void launch() {
			setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
			// TODO 从配置文件读取
			Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
			setSize(dimension.width/4, dimension.height/4);
			setLocation((dimension.width - getSize().width) / 2,
					(dimension.height - getSize().height) / 3);
			setResizable(false);
			setVisible(true);
			toFront();
			pack();
		}
	
	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(r.getString("welcome"));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText(r.getString("application.initing"));

        jLabel2.setText(r.getString("application.welcome"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
