/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaddingOption.java
 *
 * Created on 2011-5-5, 20:03:19
 */

package org.mepper.tool;

import java.awt.event.ActionEvent;

import javax.swing.Action;
import javax.swing.JToolBar;

import org.zhiwu.app.action.AbsAction;

/**
 *
 * @author root
 */
public class PaddingOption extends JToolBar {
	private CoverableTool tool ;
	private final Action singleAction = new AbsAction("uncover") {
		@Override
		public void actionPerformed(ActionEvent e) {
			if(tool != null){
				tool.setCover(false);
			}
		}
	};
	
	private final Action mutilAction = new AbsAction("cover") {
		@Override
		public void actionPerformed(ActionEvent e) {
			if(tool != null){
				tool.setCover(true);
			}
		}
	};

    public PaddingOption() {
        initComponents();
    }

	public void setTool(CoverableTool tool) {
		this.tool = tool;
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        jToggleButton1.setAction(singleAction);
        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setSelected(true);
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHideActionText(true);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jToggleButton1);

        jToggleButton2.setAction(mutilAction);
        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHideActionText(true);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jToggleButton2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables


}
