/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddGuilder_0.java
 *
 * Created on 2010-8-4, 15:04:48
 */

package org.jreader.gui;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import org.zhiwu.app.guider.AbsGuiderContent;
import org.zhiwu.app.guider.DefaultGuiderView;
import org.zhiwu.app.guider.GuiderContent;
import org.zhiwu.app.guider.GuiderContentEvent;
import org.zhiwu.utils.AppResources;

/**
 *
 * @author root
 */
public class AddGuilder_0 extends AbsGuiderContent {
	private static final long serialVersionUID = 1L;
	private static final String ID="new.guider";
	/** Creates new form AddGuilder_0 */
    public AddGuilder_0() {
        initComponents();
        
        AppResources resources=AppResources.getResources("org.jreader.app.Labels");
        resources.configGuiderContent(this,ID);
    }
    
    /* (non-Javadoc)
     * @see org.zhiwu.app.AbsGuiderContent#setGuider(org.zhiwu.app.DefaultGuiderView)
     */
    @Override
    public void setGuider(DefaultGuiderView guider) {
    	super.setGuider(guider);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        jLabel1.setText("filter:");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "package", "rss" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
	/* (non-Javadoc)
	 * @see org.zhiwu.app.GuiderContent#getNext()
	 */
	@Override
	public Class<? extends GuiderContent> getNext() {
		System.out.println(jList1.getSelectedValue());
		if(jList1.getSelectedValue().equals("package")){
			return NewPackage.class; 
		}
		return null;
	}

	/* (non-Javadoc)
	 * @see org.zhiwu.app.GuiderContent#prepare()
	 */
	@Override
	public void prepare() {
		jList1.addListSelectionListener(new ListSelectionListener() {
			@Override
			public void valueChanged(ListSelectionEvent e) {
		    	fireGuiderStateChanged(GuiderContentEvent.NextEnable,true);
			}
		});
	}

	/* (non-Javadoc)
	 * @see org.zhiwu.app.GuiderContent#finish()
	 */
	@Override
	public void finish() {
		// TODO Auto-generated method stub
		
	}


}
