/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MilitaryView.java
 *
 * Created on 2011-11-6, 22:27:52
 */
package org.chess.military.gui;

import org.chess.app.ChessViewAdapter;
import org.chess.game.GameSuperviser;
import org.chess.game.Player;
import org.chess.military.ComputerPlayer;
import org.chess.military.MilitarySuperviser;
import org.chess.military.UserPlayer;
import org.chess.military.actions.StartGameAction;

public class MilitaryView extends ChessViewAdapter {
	
	private final GameSuperviser superviser;
	
    public MilitaryView() {
    	superviser=new MilitarySuperviser();
    }
    
    @Override
    public void init() {
    	super.init();
    	initComponents();
    	newGame();
    }
    
    @Override
    protected void initActions() {
    	putAction(StartGameAction.ID, new StartGameAction(app,superviser));
    }
    
    @Override
    public void newGame() {
    	superviser.prepare();
    	superviser.register(0, new UserPlayer(1,Player.PLAYER_NAME));
    	superviser.register(1, new ComputerPlayer(2));
    	superviser.register(2, new ComputerPlayer(3));
    	superviser.register(3, new ComputerPlayer(4));
    	
    	
    	jScrollPane1.setViewportView(superviser.getBoardView().getComponent());
    	getAction(StartGameAction.ID).setEnabled(true);
    	
    	validate();
		repaint();
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

	
	
    
    
    
}
