/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutView.java
 *
 * Created on 2010-5-19, 13:13:10
 */
package org.divine.gui;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.zhiwu.app.AppDialog;
import org.zhiwu.app.Application;

/**
 *
 * @author root
 */
public class AboutView extends AppDialog {

    private static final long serialVersionUID = 7582142641032846231L;

    /** Creates new form AboutView */
    public AboutView(Application app) {
        super(app);
        initComponents();

        // setResizable(false);
        setSize(454, 272);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24));
        jLabel1.setText("先知六爻");
        jPanel2.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel2.setText("<html>　　先知六爻旨在为六爻爱好者提供断卦参考信息和辅助功能.电脑软件虽然并不能代替人来断卦，却能为其提供便利，故而开发此程序,希望能对您有所帮助．软件功能正在完善中，如果您有什么意见或者建议，希望您能告诉我．<br>　</html>");
        jPanel2.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel3.setText("<html>版本: 0.2 测试版(beta)<br>　</html>");
        jPanel2.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14));
        jLabel4.setText("<html>联系作者:<a href=\"mailto:kkliuyao@gmail.com?subject=来自先知六爻的朋友\"> kkliuyao@gmail.com<br>　</html>");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("宋体", 0, 14));
        jLabel5.setText("<html>博客:<a href=\"http://blog.sina.com.cn/kkliuyao\">http://blog.sina.com.cn/kkliuyao<br>　</html>");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);

        jLabel6.setText("All rights reserved");
        jPanel2.add(jLabel6);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel4MouseClicked
        Desktop desktop = Desktop.getDesktop();
        if (!(Desktop.isDesktopSupported() && desktop.isSupported(Desktop.Action.BROWSE))) {
            return;
        }
        try {
            URI uri = new URI("mailto:kkliuyao@gmail.com?subject=来自先知六爻的朋友");
            desktop.mail(uri);
        } catch (URISyntaxException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }// GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel5MouseClicked
        try {
            browse(new URI("http://blog.sina.com.cn/kkliuyao"));
        } catch (URISyntaxException ex) {
        }

    }// GEN-LAST:event_jLabel5MouseClicked
    private void browse(URI uri) {
        Desktop desktop = Desktop.getDesktop();
        if (!(Desktop.isDesktopSupported() && desktop.isSupported(Desktop.Action.MAIL))) {
            return;
        }
        try {
            desktop.browse(uri);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
