/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomeView.java
 *
 * Created on 2010-4-28, 15:31:54
 */

package org.divine.gui;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JFrame;

/**
 *
 * @author root
 */
public class WelcomeView extends javax.swing.JFrame {

    /** Creates new form WelcomeView */
    public WelcomeView() {
        initComponents();
        
        jProgressBar1.setValue(10);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Application is now starting...");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_END);
        jPanel1.add(jProgressBar1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Initing application");
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	WelcomeView wel=new WelcomeView();
               wel .launch();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
	/**
	 * @param newValue
	 */
	public void setText(String text) {
		jLabel1.setText(text);
		jProgressBar1.setValue(jProgressBar1.getValue()+10);
		
	}

	
	/**
	 * 
	 */
	public void launch() {
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		// TODO 从配置文件读取
		Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
		setSize(dimension.width/4, dimension.height/4);
		setLocation((dimension.width - getSize().width) / 2,
				(dimension.height - getSize().height) / 3);
		setResizable(false);
		setVisible(true);
		toFront();
		pack();
	}
	
	
}
