/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FiveRenjuView.java
 *
 * Created on 2011-11-6, 0:28:30
 */
package org.chess.renju.five.gui;

import org.chess.app.ChessViewAdapter;
import org.chess.renju.five.FiveRenju;

/**
 *
 * @author root
 */
public class FiveRenjuView extends ChessViewAdapter {
	private  FiveRenju game;
    /** Creates new form FiveRenjuView */
    public FiveRenjuView() {
//    	GameSuperviser superviser=new GameSuperviser();
//    	superviser.register(0, new AbstractPlayer(1,Player.PLAYER_NAME));
//    	superviser.register(1, new AbstractPlayer(2,Player.PLAYER_NAME));
//    	game = new FiveRenju(superviser);
    }
    
    @Override
    public void init() {
    	super.init();
    	initComponents();
    	
    	newGame();
    }
    
    @Override
    protected void initActions() {
    	
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    
    @Override
    public void newGame() {
    	game.reset();
    	jScrollPane1.setViewportView(new FiveBoardView(game));
    	
    	validate();
		repaint();
    }
}
