/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AppConfigItem.java
 *
 * Created on 2010-12-7, 23:32:27
 */

package org.zhiwu.app.config;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Locale;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

import org.zhiwu.app.AppManager;
import org.zhiwu.app.Application;
import org.zhiwu.utils.ArrayUtils;
import org.zhiwu.utils.SwingResources;

/**
 * <B>AppConfigItem</B>
 * 
 * @author Brook Tran. Email: <a href="mailto:Brook.Tran.C@gmail.com">Brook.Tran.C@gmail.com</a>
 * @version Ver 1.0.01 Jan 13, 2013 created
 * @since Application Ver 1.0
 * 
 */
public class AppConfigItem extends AbstractConfigItem {
	public static final String HANDLE_NAME_LOCALE = "app.locale";//$NON-NLS-1$
	private int localeIndex=0;
	private final SwingResources r;
	 
	private final ConfigHandle localeHandle =new AbstractConfigHandle(HANDLE_NAME_LOCALE) {
		
		@Override
		public void handle() {
			String[] s=((String)( languageCombobox.getSelectedItem())).split(" ");
			Locale l=parse(s[1]);
//			setOldValue(AppManager.getInstance().getLocale());
//			setNewValue(l);
			putPreference("locale", l.toString()); 
		}
	};
	
	/**
	 * parse a string like "zh-CN" to locale.
	 */
	private Locale parse(String locale){
		int p=locale.indexOf('_');
		return new Locale(locale.substring(0,p), locale.substring(p+1));
	}
	
	
	
	/** Creates new form AppConfigItem */
    public AppConfigItem() {
    	super("application",PreferenceManager.getInstance().getPreference(Application.class.getName()));
    	r = AppManager.getResources();
    } 
    

	@Override
	public void init() {
         initComponents();
		languageCombobox.setSelectedIndex(localeIndex);
//		countryComboBox1.setSelectedIndex(localeIndex);
		
		languageCombobox.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				if(languageCombobox.getSelectedIndex() == localeIndex){
					return;
				}
				hasUnsaveChanged=true;
				addHandle(localeHandle);
			}
		});
	}
	
	private  ComboBoxModel getListModel(){
		String[] support=getPreference("locales.support").split(",");//$NON-NLS-1$
		r.configLabel(languageLabel,"language");
//		appResources.configLabel(countryLabel, "country");
		
		Locale[] locales=Locale.getAvailableLocales();
//		String[] countrys=new String[locales.length];
		String[] languages=new String[support.length];
		
		Locale current=Locale.getDefault();
		int  p=0;
		for(int i=0,j=locales.length;i<j;i++){
//			countrys[i]=locales[i].getDisplayCountry();
			Locale l=locales[i];
			if(ArrayUtils.indexOf(support, l.toString()) == -1){
				continue;
			}
			
			languages[p]=l.getDisplayLanguage(l)+" "+l.toString();//TODO support languages: US-en,ch-ZN.
			if(current.equals(l)){
				localeIndex=p;
			}
			p++;
		}
//		countryComboBox1.setModel(new DefaultComboBoxModel(countrys));
		return new DefaultComboBoxModel(languages);
	}
	


	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        languageCombobox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        languageLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel2.setPreferredSize(new java.awt.Dimension(250, 80));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(r.getString("application.config.general.locale")));
        jPanel3.setPreferredSize(new java.awt.Dimension(380, 150));

        languageCombobox.setModel(getListModel());

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");

        languageLabel.setText(r.getString("application.config.general.locale.language"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languageLabel)
                .addGap(18, 18, 18)
                .addComponent(languageCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(languageLabel))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        jScrollPane1.setViewportView(jPanel2);

        jTabbedPane1.addTab(r.getString("application.config.general"), jScrollPane1);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox languageCombobox;
    private javax.swing.JLabel languageLabel;
    // End of variables declaration//GEN-END:variables

}
