/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreferencesView.java
 *
 * Created on 2010-4-15, 14:01:54
 */

package org.zhiwu.app.config;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.AbstractAction;
import javax.swing.AbstractListModel;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JSplitPane;
import javax.swing.ListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import org.zhiwu.app.AppDialogListener;
import org.zhiwu.app.AppManager;
import org.zhiwu.utils.AppLogging;
import org.zhiwu.utils.SwingResources;

/**
 * <B>ConfigView</B>
 * 
 * @author Brook Tran. Email: <a href="mailto:Brook.Tran.C@gmail.com">Brook.Tran.C@gmail.com</a>
 * @version Ver 1.0.01 Jan 13, 2013 created
 * @since Application Ver 1.0
 * 
 */
public class ConfigView extends javax.swing.JFrame {
	/**
	 * @uml.property  name="config"
	 * @uml.associationEnd  
	 */
	private final Config config;
	private List<ConfigItem> items;
	/**
	 * @uml.property  name="r"
	 * @uml.associationEnd  
	 */
	private final SwingResources r;
	
	/** Creates new form PreferencesView */
	public ConfigView(Config config) {
		this.config=config;
		r = AppManager.getResources();
		
		prepareItems();
		initComponents();
		init();
	}
	
	 /**
	 * 
	 */
	private void init() {
		jList1.setCellRenderer(new ConfigCellRenderer(items.toArray()));
		jList1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			@Override
			public void valueChanged(ListSelectionEvent e) {
				int p = jList1.getSelectedIndex();
				if(p == -1){
					return;
				}
				setItemPanel(items.get(p));
			}
		});
		
		if (items.size()!=0) {
			jList1.setSelectedIndex(0);
		}
		
		Action applyAction=new ConfigViewAction("application.config.apply") {//$NON-NLS-1$
			private static final long serialVersionUID = 2794711705216838820L;

			@Override
			public void actionPerformed(ActionEvent e) {
				apply();
			}
		};
		jPanel3.add(new JButton(applyAction));
		
		Action cancleAction=new ConfigViewAction("application.config.cancle") {//$NON-NLS-1$
			private static final long serialVersionUID = -2794711705216838820L;
			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		};
		jPanel3.add(new JButton(cancleAction));
		
		addWindowListener(new WindowAdapter() {
			/* (non-Javadoc)
			 * @see java.awt.event.WindowAdapter#windowClosing(java.awt.event.WindowEvent)
			 */
			@Override
			public void windowClosing(WindowEvent e) {
				dispose();
			}
		});
	}
	
	/**
	 * @param compenent
	 */
	protected void setItemPanel(ConfigItem item) {
		Component c= jSplitPane1.getRightComponent();
		jSplitPane1.remove(c);
		jSplitPane1.add(item.getCompenent(), JSplitPane.RIGHT);
	}

	public void apply(){
		for (ConfigItem item : items) {
			if(item.hasUnsaveChanged()){
				item.handleChanged();
			}
		}
		dispose();
	}

	/**
	 * @return
	 */
	private ListModel getListModel() {
		return new AbstractListModel() {
			private static final long serialVersionUID = 2715085950774978774L;
			@Override
			public int getSize() {
				return items.size();
			}
			@Override
			public Object getElementAt(int index) {
				return items.get(index);
			}
		};
	}
	

	/**
	 * 
	 */
	private void prepareItems() {
		List<Class<? extends ConfigItem>> itemClass=config.getItems();
		items=new ArrayList<ConfigItem>();
		for (Class<? extends ConfigItem> c:itemClass) {
			ConfigItem item;
			try {
				item = c.newInstance();
				item.init();
				item.addConfigListener(config.getListener(c));
				items.add(item);
			} catch (InstantiationException e) {
				AppLogging.handleException(e);
			} catch (IllegalAccessException e) {
				AppLogging.handleException(e);
			}
		}
	}


	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 350));

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setDividerSize(4);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 100));

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Preference"));
        jList1.setModel(getListModel());
        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jScrollPane2.setBorder(null);
        jSplitPane1.setRightComponent(jScrollPane2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText(r.getString("application.config.view.tips.restart"));
        jPanel1.add(jLabel1);

        jPanel2.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

	/**
	 * @param iDialogListener
	 */
	public void showDialog(AppDialogListener iDialogListener) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				setVisible(true);
			}
		});
	}

	public abstract class ConfigViewAction extends AbstractAction {
		private static final long serialVersionUID = 1L;

		/**
	 * 
	 */
		public ConfigViewAction(String ID) {
			super(ID);
			r.configAction(this, ID);
		}
	}
}
