/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResourcesConfigItem.java
 *
 * Created on 2011-4-16, 14:22:10
 */

package org.mepper.resources.gui;

import org.mepper.editor.gui.MapView;
import org.zhiwu.app.config.AbstractConfigItem;
import org.zhiwu.app.config.PreferenceManager;

/**
 *
 * @author root
 */
public class ResourcesConfigItem extends AbstractConfigItem {

    /** Creates new form ResourcesConfigItem */
    public ResourcesConfigItem() {
       super("map.resource", PreferenceManager.getInstance().getPreference(MapView.class.getName()));
    }
    
    @Override
    public void init() {
    	 initComponents();    	
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
