package com.test.bean;

import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

import javax.swing.BoxLayout;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * 类<B> CustomerLoan </B>是
 * <p>
 * The following class is used by Earnest Bank to accept the details of
 * customers who take loans. Whenever a new loan type is added to the database,
 * the loan type should be made available to the user. /* This class traps the
 * property change event generated by the Loan class and adds the new loan type
 * to its loan type combo box.
 * 
 * @author Brook Tran. Email: <a href="mailto:brook.tran.c@gmail.com">brook.tran.c@gmail.com</a>
 * @version Ver 1.0 2009-3-6 新建
 * @since chenzhw Ver 1.0
 * 
 */
public class CustomerLoan  implements PropertyChangeListener{
	private static JFrame frame;
	private JPanel mPanel,chPanel,mmPanel;
	private Loan loan;
	private BoxLayout bLayout;
	private JLabel lblCustomerName,lblCustomerType;
	private JTextField txtName;
	private JComboBox cbbType;

	public CustomerLoan(){
		mPanel=new JPanel();
		chPanel=new JPanel();
		mmPanel=new JPanel();
		loan=new Loan();
		mmPanel.setLayout(new FlowLayout());
		mmPanel.add(loan);
		mmPanel.add(chPanel);
		frame.getContentPane().add(mmPanel);/////
		
		lblCustomerName=new JLabel("Customer Name:");
		lblCustomerType=new JLabel("Type of Loan token:");
		
		txtName=new JTextField(16);
		cbbType=new JComboBox();
		cbbType.addItem(loan.getLoanType());
		chPanel.setLayout(new GridLayout(2,2));
		chPanel.add(lblCustomerName);
		chPanel.add(txtName);
		chPanel.add(lblCustomerType);
		chPanel.add(cbbType);
		
		loan.addPropertyChangeListener(this);// must implements PropertyChangeListener interface
	}

	/**
	 * @see java.beans.PropertyChangeListener#propertyChange(java.beans.PropertyChangeEvent)
	 */
	public void propertyChange(PropertyChangeEvent evt) {
		System.out.println(" method propertyChange() was called");
		cbbType.addItem(evt.getNewValue());//////????
	}
	
	public static void main(String[] args) {
		frame=new JFrame("Loan -- for test JavaBean");
		new CustomerLoan();
		frame.setSize(400,400);
		frame.setVisible(true);
	}
}
































