/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiaryView.java
 *
 * Created on 2011-6-19, 22:33:29
 */

package org.jtools.diary.gui;

import org.zhiwu.app.AbsView;

public class DiaryView extends AbsView {

    /** Creates new form DiaryView */
    public DiaryView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        diaryEditor1 = new org.jtools.diary.gui.DiaryEditorView();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setRightComponent(diaryEditor1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jtools.diary.gui.DiaryEditorView diaryEditor1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

}
